### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Zain-ul-din** [iMohammadd/gardener-app#1]
@iMohammadd AOA! can i talk with you. i want to discuss something with you.

**Comment by iMohammadd** [comment]
@Zain-ul-din yeah bro, wassup?

**Comment by Zain-ul-din** [comment]
I'm fine. how are you? are you the owner of `Aries-Dev` org and are you maintaining it anymore?

**Comment by iMohammadd** [comment]
@Zain-ul-din yeah, it was a personal project, but i have no time to maintain it any longer

**Comment by Zain-ul-din** [comment]
I plan to make a software agency after 6 month of struggle with naming. i ended up `Aries-Dev`. if you are no longer maintaining it can I get that org it would be very helpful for me.

**Comment by iMohammadd** [comment]
@Zain-ul-din no

**Comment by Zain-ul-din** [comment]
ok no problem. thank you
